exames/urls.py
from django.urls import path
from . import views

app_name = 'exames'

urlpatterns = [
    path('solicitar_exames/',  views.solicitar_exames, name='solicitar_exames'),
    path('fechar_pedido/',  views.fechar_pedido, name='fechar_pedido'),
    path('gerenciar_pedidos/',  views.gerenciar_pedidos, name='gerenciar_pedidos'),
    path('cancelar_pedido/<int:pedido_id>',  views.cancelar_pedido, name='cancelar_pedido'),
    path('gerenciar_exames/', views.gerenciar_exames, name="gerenciar_exames"),
    path('permitir_abrir_exame/<int:exame_id>', views.permitir_abrir_exame, name="permitir_abrir_exame"),
    path('solicitar_senha_exame/<int:exame_id>', views.solicitar_senha_exame, name="solicitar_senha_exame"),
    path('gerar_acesso_medico/', views.gerar_acesso_medico, name="gerar_acesso_medico"),
    path('acesso_medico/<str:token>', views.acesso_medico, name='acesso_medico'),
]

vitalab/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls')),
    path('exames/', include('exames.urls')),
    path('empresarial/', include('empresarial.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exames/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe
from django.utils import timezone
from django.conf import settings
from secrets import token_urlsafe
from datetime import timedelta
import datetime

TIPO_CHOICES = (
    ('I', 'Exame de imagem'),
    ('S', 'Exame de sangue'),
)

STATUS_CHOICES = (
    ('E', 'Em análise'),
    ('F', 'Finalizado')
)

class TiposExame(models.Model):
    nome = models.CharField(max_length=50)
    tipo = models.CharField(max_length=1, choices=TIPO_CHOICES)
    preco = models.FloatField()
    disponivel = models.BooleanField(default=True)
    horario_inicial = models.IntegerField()
    horario_final = models.IntegerField()

    def __str__(self):
        return self.nome

class SolicitacaoExame(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    tipo_exame = models.ForeignKey(TiposExame, on_delete=models.DO_NOTHING)
    status = models.CharField(max_length=2, choices=STATUS_CHOICES)
    resultado = models.FileField(upload_to="resultados", null=True, blank=True)
    requer_senha = models.BooleanField(default=False)
    senha = models.CharField(max_length=6, null=True, blank=True)
  
    def badge_template(self):
        if self.status == "E":
            classes = 'bg-warning text-dark'
            text = 'Em análise'
        elif self.status == "F":
            classes = 'bg-success'
            text = 'Finalizado'
        
        return mark_safe(f'<span class="badge {classes}">{text}</span>')
        

    def __str__(self):
        return f'{self.usuario} | {self.tipo_exame.nome}'

class PedidosExame(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    solicitacao_exames = models.ManyToManyField(SolicitacaoExame)
    agendado = models.BooleanField(default=True)
    data = models.DateField(default=datetime.datetime.now)
    
    def __str__(self):
        return f'{self.usuario} | {self.data}'

class AcessoMedico(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    identificacao = models.CharField(max_length=50)
    tempo_de_acesso = models.IntegerField() # Em horas
    criado_em = models.DateTimeField(default=datetime.datetime.now)
    data_exames_iniciais = models.DateField()
    data_exames_finais = models.DateField()
    token = models.CharField(max_length=20, null=True, blank=True)

    @property 
    def status(self):
        return 'Expirado' if timezone.now() > (self.criado_em + timedelta(hours=self.tempo_de_acesso)) else 'Ativo'
        
    @property
    def url(self):
        return f'{settings.URL_LINKS}exames/acesso_medico/{self.token}'

    def save(self, *args, **kwargs):
        if not self.token:
            self.token = token_urlsafe(6)

        super(AcessoMedico, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.token

exames/forms.py
from django import forms 
from . import models

class AcessoMedicoForm(forms.ModelForm):
    class Meta:
        model=models.AcessoMedico
        fields = ('identificacao', 'tempo_de_acesso', 'data_exames_iniciais', 'data_exames_finais',)


'''
   
    identificacao = models.CharField(max_length=50)
    tempo_de_acesso = models.IntegerField() # Em horas
    data_exames_iniciais = models.DateField()
    data_exames_finais = models.DateField()
'''

exames/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.messages import constants
from django.contrib import messages
from .forms import AcessoMedicoForm
from .models import TiposExame, PedidosExame, SolicitacaoExame, AcessoMedico
import datetime

@login_required(login_url='/usuarios/logar')
def solicitar_exames(request):
    tipos_exames = TiposExame.objects.all()
    data = datetime.datetime.now()

    if request.POST:
        exames_ids = request.POST.getlist('exames')
        solicitacao_exames = TiposExame.objects.filter(id__in=exames_ids) 
        preco_total = sum(exame.preco for exame in solicitacao_exames if exame.disponivel)

        context = {
            'tipos_exames': tipos_exames,
            'solicitacao_exames': solicitacao_exames,
            'preco_total': preco_total,
            'data': data,
        }
        return render(request, 'solicitar_exames.html', context)   
    return render(request, 'solicitar_exames.html', {'tipos_exames': tipos_exames, 'data': data})


@login_required(login_url='/usuarios/logar')
def fechar_pedido(request):
    if request.POST:
        exames_id = request.POST.getlist('exames')
        tipos_exames = TiposExame.objects.filter(id__in=exames_id)
        pedidos_exame = PedidosExame.objects.create(usuario=request.user)
        solicitacao_exames_temp = [
            SolicitacaoExame(usuario=request.user, tipo_exame=tipo_exame, status='E')
            for tipo_exame in tipos_exames
        ]
        SolicitacaoExame.objects.bulk_create(solicitacao_exames_temp)
        pedidos_exame.solicitacao_exames.set(solicitacao_exames_temp)
        messages.add_message(request, constants.SUCCESS, 'Pedido de exame realizado com sucesso!')
        return redirect('/exames/gerenciar_pedidos/')
    return redirect('solicitar_exames')


@login_required(login_url='/usuarios/logar')
def gerenciar_pedidos(request):
    pedidos_exames = PedidosExame.objects.filter(usuario=request.user)
    return render(request, 'gerenciar_pedidos.html', {'pedidos_exames': pedidos_exames})


@login_required(login_url='/usuarios/logar')
def cancelar_pedido(request, pedido_id):
    pedido = PedidosExame.objects.get(id=pedido_id)
    if not  request.user == pedido.usuario:
        messages.add_message(request, constants.ERROR, 'Usuário não tem permissão para cancelar o pedido!')
        return redirect('/exames/gerenciar_pedidos/')
    pedido.agendado = False
    pedido.save()
    messages.add_message(request, constants.SUCCESS, 'Pedido de exame cancelado com sucesso!')
    return redirect('/exames/gerenciar_pedidos/')


@login_required(login_url='/usuarios/logar')
def gerenciar_exames(request):
    exames = SolicitacaoExame.objects.filter(usuario=request.user)
    return render(request, 'gerenciar_exames.html', {'exames':exames})


@login_required(login_url='/usuarios/logar')
def permitir_abrir_exame(request, exame_id):
    exame = SolicitacaoExame.objects.get(id=exame_id)
    if not exame.requer_senha:
        try:
            return redirect(exame.resultado.url)
        except:
            messages.add_message(request, constants.ERROR, 'PDF do exame não foi cadastrado!')
            return redirect('exames:gerenciar_exames')
    return redirect(f'/exames/solicitar_senha_exame/{exame_id}')


@login_required(login_url='/usuarios/logar')
def solicitar_senha_exame(request, exame_id):
    exame = SolicitacaoExame.objects.get(id=exame_id)
    if request.POST:
        senha = request.POST.get('senha')
        if senha == exame.senha:
          try:
            return redirect(exame.resultado.url)
          except:
            messages.add_message(request, constants.ERROR, 'PDF do exame não foi cadastrado!')
            return redirect('exames:gerenciar_exames')
        else:
            messages.add_message(request, constants.ERROR, 'Senha inválida.')
            return redirect('exames:solicitar_senha_exame', exame_id=exame.id)
    return render(request, 'solicitar_senha_exames.html', {'exame': exame})


@login_required(login_url='/usuarios/logar')
def gerar_acesso_medico(request):
    form = AcessoMedicoForm()
    acessos_medicos = AcessoMedico.objects.filter(usuario=request.user)
    if request.POST:
        form = AcessoMedicoForm(request.POST)
        if form.is_valid():
            acessoMedico = form.save(commit=False)
            acessoMedico.usuario = request.user
            form.save()
            messages.add_message(request, constants.SUCCESS, 'Acesso gerado com sucesso!')
            return redirect('exames:gerar_acesso_medico')
        return render(request, 'gerar_acesso_medico.html', {'form': form, 'acessos_medicos': acessos_medicos})
    return render(request, 'gerar_acesso_medico.html', {'form': form, 'acessos_medicos': acessos_medicos})
    

def acesso_medico(request, token):
    acesso_medico = AcessoMedico.objects.get(token=token)
    if acesso_medico.status == 'Expirado':
        messages.add_message(request, constants.ERROR, 'Esse token já expirou, solicite outro.')
        if request.user.is_authenticated:
            return redirect('exames:gerar_acesso_medico')
        return redirect('/usuarios/logar')
    
    pedidos = PedidosExame.objects.filter(usuario=acesso_medico.usuario)\
                                .filter(data__gte=acesso_medico.data_exames_iniciais)\
                                .filter(data__lte=acesso_medico.data_exames_finais)
    print(pedidos)
    return render(request, 'acesso_medico.html', {'pedidos': pedidos})

exames/templates/acesso_medico.html
{% extends "bases/base.html" %}
{% load static %}

{% block 'head' %}
    <link href="{% static 'exames/css/css.css' %}" rel="stylesheet">
    <link href="{% static 'exames/css/gerenciar_pedidos.css' %}" rel="stylesheet">
{% endblock 'head' %}


{% block 'conteudo' %}
    <br>
    <br>
    <div class="container">

        
        <table style="">
            <tr>
              <th>Id</th>
              <th>Exame</th>
              
            </tr>
			
            {% for pedido in pedidos %}
                {% for exame in pedido.solicitacao_exames.all %}
                    <tr class="linha-tabela">
                        <td>{{exame.tipo_exame.nome}}</td>
                        {% if exame.resultado %}
                            <td><a style="text-decoration: none;"
                                 href="{{exame.resultado.url}}" class="btn-secundario">Ver exame</a>
                            </td>
                        {% else %}
                            <td>Em análise</td>
                        {% endif %}
                    </tr>
                {% endfor %}
            {% endfor %}
           
           
        </table>
    </div>
{% endblock 'conteudo' %}

exames/templates/gerar_acesso_medico.html
{% extends "bases/base.html" %}
{% load static %}

{% block 'head' %}
    <link href="{% static 'exames/css/css.css' %}" rel="stylesheet">
    <link href="{% static 'exames/css/gerenciar_pedidos.css' %}" rel="stylesheet">
{% endblock 'head' %}


{% block 'conteudo' %}
    <br>
    <br>
    <div class="container">
        {% if messages %}
            <br>
            {% for message in messages %}
            <div class="alert {{ message.tags }}">{{ message }}</div>
            {% endfor %}
        {% endif %}
        <div class="row">
            <div class="col-md-5">
                <h3>Gerar acesso médico</h3>

                <form action="{{ form_action }}" method="POST">
                    {% csrf_token %}

                    <label for="">Identificação</label>
                    <br>
                    <input style="width: 100%" type="text" name="{{form.identificacao.name}}" id="" class="input-default">
                    {% if form.identificacao.errors %}
                        {% for error in form.identificacao.errors  %}
                            <p class="help is-danger">{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                    <br>
                    <br>
                    <label for="">Tempo de acesso (em horas)</label>
                    <br>
                    <input style="width: 100%" type="number" name="{{form.tempo_de_acesso.name}}" id="" class="input-default">
                    {% if form.tempo_de_acesso.errors %}
                        {% for error in form.tempo_de_acesso.errors  %}
                            <p class="help is-danger">{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                    <br>
                    <br>
                    <div class="row">
                        <label for="">Acesso a exames realizados entre:</label>
                        <div class="col-md">
                            <input style="width: 100%" type="date" name="{{form.data_exames_iniciais.name}}" id="" class="input-default">
                            {% if form.data_exame_inicial.errors %}
                                {% for error in form.data_exame_inicial.errors  %}
                                    <p class="help is-danger">{{ error }}</p>
                                {% endfor %}
                            {% endif %}
                        </div>
                        <div class="col-md">
                            <input style="width: 100%" type="date" name="{{form.data_exames_finais.name}}" id="" class="input-default">
                            {% if form.data_exame_final.errors %}
                                {% for error in form.data_exame_final.errors  %}
                                    <p class="help is-danger">{{ error }}</p>
                                {% endfor %}
                            {% endif %}
                            <br>
                            <br>
                        </div>
                   
                        
                    </div>
                    <input style="width: 40%" type="submit" class="btn-default" value="Gerar link">
                </form>
            </div>
            <div class="col-md">
                
                <div class="card">
                    <table style="text-align: center">
                        <tr>
                          <th>Id</th>
                          <th>Status</th>
                          <th>Link</th>
                          
                        </tr>
        
                       {% for acesso in  acessos_medicos%}
                            <tr class="linha-tabela">
                                <td>{{acesso.identificacao}}</td>
                                <td>{{acesso.status}}</td>
                                <td><a href="{{acesso.url}}">{{acesso.url}}</a></td>
                            </tr>
                        {% endfor %}
                    
                       
                    </table>
                </div>

            </div>
        </div>
    </div>
{% endblock 'conteudo' %}

exames/templates/gerenciar_exames.html
{% extends "bases/base.html" %}
{% load static %}

{% block 'head' %}
    <link href="{% static 'exames/css/css.css' %}" rel="stylesheet">
    <link href="{% static 'exames/css/gerenciar_pedidos.css' %}" rel="stylesheet">
    <link href="{% static 'exames/css/gerenciar_exames.css' %}" rel="stylesheet">
{% endblock 'head' %}


{% block 'conteudo' %}
    <br> 
    <br>
    <div class="container">
        {% if messages %}
            <br>
            {% for message in messages %}
            <div class="alert {{ message.tags }}">{{ message }}</div>
            {% endfor %}
        {% endif %}
        <div class="card card-view">
            
            <div class="sub-card">
                <h3>Exames de sangue</h3>
                <hr>
                <br>
                {% for exame in exames  %}
                    {% if exame.tipo_exame.tipo == 'S' %}
                        <div class="row">
                            <div class="col-md">{{exame.tipo_exame.nome}}</div>
                            <div class="col-md">
                                {{ exame.badge_template}}
                            </div>
                            <div class="col-md">
                                {% if exame.status == 'F' %}                                               
                                    <a href="{% url 'exames:permitir_abrir_exame' exame.id %}" class="btn btn-light">Abrir</a>
                                {% else %}
                                    <a href="#" class="btn btn-light disabled">Abrir</a>
                                {% endif %}
                            </div>
                        </div>
                        <br>
                    {% endif %}
                {% endfor %}
            </div>
            <br>
            <br>
            <div class="sub-card">
                <h3>Exames de imagem</h3>
                <hr>
                <br>
                {% for exame in exames  %}
                    {% if exame.tipo_exame.tipo == 'I' %}
                        <div class="row">
                            <div class="col-md">{{exame.tipo_exame.nome}}</div>
                            <div class="col-md">
                                {{ exame.badge_template}}
                            </div>
                            <div class="col-md">
                                {% if exame.status == 'F' %}                                               
                                    <a href="{% url 'exames:permitir_abrir_exame' exame.id %}" class="btn btn-light">Abrir</a>
                                {% else %}
                                    <a href="#" class="btn btn-light disabled">Abrir</a>
                                {% endif %}
                            </div>
                        </div>
                        <br>
                    {% endif %}
                {% endfor %}
            </div>
            
        </div>

    </div>

{% endblock 'conteudo' %}

exames/templates/gerenciar_pedidos.html
{% extends "bases/base.html" %}
{% load static %}

{% block 'head' %}
    <link href="{% static 'exames/css/css.css' %}" rel="stylesheet">
    <link href="{% static 'exames/css/gerenciar_pedidos.css' %}" rel="stylesheet">
{% endblock 'head' %}


{% block 'conteudo' %}
    <br> 
    <br>
    <div class="container">
        {% if messages %}
            <br>
            {% for message in messages %}
            <div class="alert {{ message.tags }}">{{ message }}</div>
            {% endfor %}
        {% endif %}
        <div class="card card-view">
            <table>
                <tr>
                  <th>Solicitação</th>
                  <th>Data</th>
                  <th>Exames</th>
                  <th>Ação</th>
                </tr>

                {% for pedidos in pedidos_exames %}
                    <tr class="linha-tabela">
                        <td>{{pedidos.id}}</td>
                        <td>{{pedidos.data}}</td>
                        <td>
                            <select class="form-select">
                                {% for solic_exame in pedidos.solicitacao_exames.all %}
                                    <option style="color: black"  value="">{{solic_exame.tipo_exame.nome}}</option>
                                {% endfor %}
                            </select>
                        </td>
                        <td>
                         
                            <a href="{% url 'exames:cancelar_pedido' pedidos.id %}"  class="btn btn-danger {% if not pedidos.agendado %} disabled {% endif %}">Cancelar</a>
                        </td>
                    </tr>
                {% endfor %}
               
              </table>
              
            
        </div>

    </div>

{% endblock 'conteudo' %}

exames/templates/solicitar_exames.html
{% extends "bases/base.html" %}
{% load static %}


{% block 'head' %}
    <link href="{% static 'exames/css/css.css' %}" rel="stylesheet"> 
{% endblock 'head' %}

{% block 'conteudo' %}
<br>
<br>
<div class="container">
    <div class="row">
        <div class="col-md">
            <h3 class="font-destaque">Solicitar exames</h3>
           

           
            <form action="{% url 'exames:solicitar_exames' %}" method="POST">
                {% csrf_token %}
                <label for="">Selecione os exames para realizar</label>
                <select class="select form-control bg-select" multiple name="exames">
                    {% for exame in tipos_exames%}
                        <option class="opt" value="{{exame.id}}">{{exame.nome}}</option>
                    {% endfor %}
                </select>
                <br>
                <input type="submit" class="btn-default tamanho-2" name="ultimo_nome" value="Solicitar exames">
            </form>
        </div>
        <div class="col-md-2">
        </div>
       
        <div class="col-md card">
            {% if solicitacao_exames %}
                {% for exame in solicitacao_exames %}
                    <div style="font-size: 20px; font-weight: bold">
                        {% if exame.disponivel %}
                            <img src="{% static 'exames/img/check.png' %}">
                        {% else %}
                            <img src="{% static 'exames/img/exit.png' %}">
                        {% endif %}
                        {{exame.nome}}
                        <span class="previa-preco">
                            R$ {{exame.preco}}
                        </span>
                    </div>
                {% endfor %}

                <hr style="color: white;">
                <div>
                    <label>Total: </label><label class="previa-preco">R$ {{preco_total}}</label>
                </div>
                <br>
                <h5>Data: {{ data.day }} de {{ data|date:"F" }}</h5>
                <br>
                <form action="{% url 'exames:fechar_pedido' %}" method="POST">
                    {% csrf_token %}
                    {% for exame in solicitacao_exames %}
                        <input type="hidden" value="{{ exame.id }}" name="exames">
                    {% endfor %}
                    <button class="btn-secundario">Fechar pedido</button>
                </form>
            
            {% else %}
                <h3>Nenhum exame selecionado</h3>
            {% endif %}
        </div>

    </div>
</div>
{% endblock 'conteudo' %}

exames/templates/solicitar_senha_exames.html
{% extends "bases/base.html" %}
{% load static %}

{% block 'head' %}
    <link href="{% static 'exames/css/css.css' %}" rel="stylesheet">
    <link href="{% static 'exames/css/gerenciar_pedidos.css' %}" rel="stylesheet">
    <link href="{% static 'exames/css/gerenciar_exames.css' %}" rel="stylesheet">
{% endblock 'head' %}


{% block 'conteudo' %}
    <br><br>
    
    <div class="container">
        {% if messages %}
            <br>
            {% for message in messages %}
            <div class="alert {{ message.tags }}">{{ message }}</div>
            {% endfor %}
        {% endif %}
        <h3>{{exame.exame.nome}}</h3>
        <br>
        <form action="{% url "exames:solicitar_senha_exame" exame.id %}" method="POST">{% csrf_token %}
            
            <label>Senha de acesso</label>
            <br>
            <input type="password" name="senha" class="form-control" style="width: 40%">
            <br>

            <input type="submit" class="btn-default">
            
        </form>
        
    </div>

{% endblock 'conteudo' %}