empresarial/urls.py
from django.urls import path
from . import views

app_name = 'empresarial'

urlpatterns = [
    path('gerenciar_clientes/', views.gerenciar_clientes, name="gerenciar_clientes"),
    path('cliente/<int:cliente_id>', views.cliente, name="cliente"),
    path('exame_cliente/<int:exame_id>', views.exame_cliente, name="exame_cliente"),
    path('proxy_pdf/<int:exame_id>', views.proxy_pdf, name="proxy_pdf"),
    path('gerar_senha/<int:exame_id>', views.gerar_senha, name="gerar_senha"),
    path('alterar_dados_exame/<int:exame_id>', views.alterar_dados_exame, name="alterar_dados_exame"),
]

exames/urls.py
from django.urls import path
from . import views

app_name = 'exames'

urlpatterns = [
    path('solicitar_exames/',  views.solicitar_exames, name='solicitar_exames'),
    path('fechar_pedido/',  views.fechar_pedido, name='fechar_pedido'),
    path('gerenciar_pedidos/',  views.gerenciar_pedidos, name='gerenciar_pedidos'),
    path('cancelar_pedido/<int:pedido_id>',  views.cancelar_pedido, name='cancelar_pedido'),
    path('gerenciar_exames/', views.gerenciar_exames, name="gerenciar_exames"),
    path('permitir_abrir_exame/<int:exame_id>', views.permitir_abrir_exame, name="permitir_abrir_exame"),
    path('solicitar_senha_exame/<int:exame_id>', views.solicitar_senha_exame, name="solicitar_senha_exame"),
    path('gerar_acesso_medico/', views.gerar_acesso_medico, name="gerar_acesso_medico"),
    path('acesso_medico/<str:token>', views.acesso_medico, name='acesso_medico'),
]

vitalab/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls')),
    path('exames/', include('exames.urls')),
    path('empresarial/', include('empresarial.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empresarial/models.py
from django.db import models

# Create your models here.

empresarial/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.db.models.functions import Concat
from django.db.models import Value
from django.contrib.messages import constants
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from exames.models import SolicitacaoExame
from django.http import FileResponse, HttpResponse
from .utils import gerar_pdf_exames, gerar_senha_aleatoria

@staff_member_required
def gerenciar_clientes(request):
    clientes = User.objects.filter(is_staff=False)

    nome_completo = request.GET.get('nome')
    email = request.GET.get('email')

    if email:
        clientes = clientes.filter(email__icontains=email)
    if nome_completo:
        clientes = clientes.annotate(full_name=Concat('first_name', Value(' '), 'last_name')).filter(full_name__contains=nome_completo)

    return render(request, 'gerenciar_clientes.html', {'clientes': clientes})


@staff_member_required 
def cliente(request, cliente_id):
    cliente = User.objects.get(id=cliente_id)
    exames = SolicitacaoExame.objects.filter(usuario=cliente)
    return render(request, 'cliente.html', {'cliente': cliente, 'exames': exames})


@staff_member_required 
def exame_cliente(request, exame_id):
    exame = SolicitacaoExame.objects.get(id=exame_id)
    return render(request, 'exame_cliente.html', {'exame': exame})


@staff_member_required 
def proxy_pdf(request, exame_id):
    exame = SolicitacaoExame.objects.get(id=exame_id)

    response = exame.resultado.open()
    return FileResponse(response)

def gerar_senha(request, exame_id):
    exame = SolicitacaoExame.objects.get(id=exame_id)

    if exame.senha:
        return FileResponse(gerar_pdf_exames(exame.tipo_exame.nome, exame.usuario.first_name, exame.senha)\
                            , filename="token.pdf")
    
    exame.senha = gerar_senha_aleatoria(9)
    exame.requer_senha = True
    exame.save()
    return FileResponse(gerar_pdf_exames(exame.tipo_exame.nome, exame.usuario.first_name, exame.senha)\
                        , filename="token.pdf")


@staff_member_required 
def alterar_dados_exame(request, exame_id):
    exame = SolicitacaoExame.objects.get(id=exame_id)

    pdf = request.FILES.get('resultado')
    status = request.POST.get('status')
    requer_senha = request.POST.get('requer_senha')
    
    if requer_senha and (not exame.senha):
        messages.add_message(request, constants.ERROR, 'Para exigir a senha primeiro crie uma.')
        return redirect(f'/empresarial/exame_cliente/{exame_id}')
    
    exame.requer_senha = True if requer_senha else False

    if pdf:
        exame.resultado = pdf
        
    exame.status = status
    exame.save()
    messages.add_message(request, constants.SUCCESS, 'Alteração realizada com sucesso')
    return redirect(f'/empresarial/exame_cliente/{exame_id}')

empresarial/templates/cliente.html
{% extends "bases/base.html" %}
{% load static %}

{% block 'head' %}
    <link href="{% static 'exames/css/css.css' %}" rel="stylesheet">
    <link href="{% static 'exames/css/gerenciar_pedidos.css' %}" rel="stylesheet">
    <link href="{% static 'exames/css/gerenciar_exames.css' %}" rel="stylesheet">
{% endblock 'head' %}


{% block 'conteudo' %}
    <br> 
    <br>
    <div class="container">
        {% if messages %}
            <br>
            {% for message in messages %}
            <div class="alert {{ message.tags }}">{{ message }}</div>
            {% endfor %}
        {% endif %}
        <h3 class="font-destaque">{{cliente.get_full_name}}</h3>
        <p>{{cliente.email}}</p>
        <div class="card card-view">
            
            <div class="sub-card">
                <h3>Exames de sangue</h3>
                <hr>
                <br>
                {% for exame in exames  %}
                    {% if  exame.tipo_exame.tipo == 'S'%}
                        <div class="row">
                            <div class="col-md"><h3>{{exame.tipo_exame.nome}}</h3></div>
                            <div class="col-md">{{exame.badge_template}}</div>
                            <div class="col-md">
                                <a href="{% url "empresarial:exame_cliente" exame.id %}" class="btn btn-light">Abrir</a>
                            </div>
                        </div>
                        <br>
                    {% endif %}
                {% endfor %}
            </div>
            <br>
            <br>
            <div class="sub-card">
                <h3>Exames de imagem</h3>
                <hr>
                <br>
                {% for exame in exames  %}
                    {% if  exame.tipo_exame.tipo == 'I'%}
                        <div class="row">
                            <div class="col-md"><h3>{{exame.tipo_exame.nome}}</h3></div>
                            <div class="col-md">{{exame.badge_template}}</div>
                            <div class="col-md"><a href="{% url "empresarial:exame_cliente" exame.id %}" class="btn btn-light">Abrir</a></div>
                        </div>
                        <br>
                    {% endif %}
                {% endfor %}
            </div>
            
        </div>

    </div>

{% endblock 'conteudo' %}

empresarial/templates/exame_cliente.html
{% extends "bases/base.html" %}
{% load static %}

{% block 'head' %}
    <link href="{% static 'exames/css/css.css' %}" rel="stylesheet">
    <link href="{% static 'exames/css/gerenciar_pedidos.css' %}" rel="stylesheet">
    <link href="{% static 'exames/css/gerenciar_exames.css' %}" rel="stylesheet">
{% endblock 'head' %}


{% block 'conteudo' %}
    <br>
    <div class="container">
        {% if messages %}
            <br>
            {% for message in messages %}
            <div class="alert {{ message.tags }}">{{ message }}</div>
            {% endfor %}
        {% endif %}
        <div class="row">
        <h3 class="font-destaque">{{exame.usuario.get_full_name}}</h3>
        <p>{{exame.usuario.email}}</p>
        <br>
        <div class="row">
            <div class="col-md-6">
                <form action="{% url 'empresarial:alterar_dados_exame' exame.id %}"
                        method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="FILE" value="Alterar PDF" class="btn-secundario" name="resultado">
               
                    <br>
                    <br>
                    {% if exame.resultado %}
                        <a style="width: 100%;" href="{{exame.resultado.url}}" target="__blank"><div  style="width: 100%;" id="pdf-container"></div></a>
                    {% endif %}
            </div>
            <div class="col-md-6">
                <h3>Status</h3>

                <select name="status" id="" class="form-select">
                    <option style="color: black;" {% if exame.status == "E" %}selected{% endif %} value="E">Em análise</option>
                    <option style="color: black;" {% if exame.status == "F" %}selected{% endif %} value="F">Finalizado</option>
                </select>
                <br>
                <input type="checkbox" name="requer_senha" id="" {% if exame.requer_senha %}checked{% endif %}><label for="">Requer senha para acessar ?</label>
                <br>
                <br>

                <input type="submit" value="Salvar" class="btn-default">
                </form>
                <a style="text-decoration: none;" href="{% url 'empresarial:gerar_senha' exame.id %}" class="btn-secundario">Gerar senha</a>
            </div>
        </div>
        
    </div>


<script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.11.338/pdf.min.js"></script>
<script>

    const container = document.getElementById('pdf-container');

    pdfjsLib.getDocument("{% url 'empresarial:proxy_pdf' exame.id %}").promise.then(pdf => {
        pdf.getPage(1).then(page => {
            const canvas = document.createElement('canvas');
            const context = canvas.getContext('2d');
            const viewport = page.getViewport({ scale: 0.6 });

            canvas.width = viewport.width;
            canvas.height = viewport.height;

            page.render({ canvasContext: context, viewport }).promise.then(() => {
                container.appendChild(canvas);
            });
        });
    });
</script>

{% endblock 'conteudo' %}

empresarial/templates/gerenciar_clientes.html
{% extends "bases/base.html" %}
{% load static %}

{% block 'head' %}
    <link href="{% static 'exames/css/css.css' %}" rel="stylesheet">
    <link href="{% static 'exames/css/gerenciar_pedidos.css' %}" rel="stylesheet">
{% endblock 'head' %}


{% block 'conteudo' %}
    <br> 
    <br>
    <div class="container">
        {% if messages %}
            <br>
            {% for message in messages %}
                <div class="alert {{ message.tags }}">{{ message }}</div>
            {% endfor %}
        {% endif %}
        <div class="row">
            <div class="col-md">
                <form action="{% url "empresarial:gerenciar_clientes" %}" method="GET">
                <label for="">Nome</label>
                <input type="text" class="form-control" name="nome" value="{{nome_completo}}">
            </div>
            <div class="col-md">
                <label for="">E-mail</label>
                <input type="text" class="form-control" name="email" value="{{email}}">
            </div>
            <div class="col-md">
                <br>
                <input type="submit" class="btn-default">
                </form>

            </div>
        </div>
        <br>
        <div class="card card-view">
            <table>
                <tr>
                  <th>Nome</th>
                  <th>E-mail</th>
                  <th>CPF</th>
                </tr>

                {% for cliente in clientes %}
                    <tr class="linha-tabela">
                        <td><a href="{% url 'empresarial:cliente' cliente.id %}">{{cliente.get_full_name}}</a></td>
                        <td>{{cliente.email}}</td>
                        
                        <td>
                        
                        </td>
                    </tr>
                {% endfor %}
               
              </table>
              
            
        </div>

    </div>

{% endblock 'conteudo' %}